export const LiquityV2SPStrategy = [
  {
    "type": "constructor",
    "inputs": [
      { "name": "_addressesRegistry", "type": "address", "internalType": "address" },
      { "name": "_asset", "type": "address", "internalType": "address" },
      { "name": "_auctionFactory", "type": "address", "internalType": "address" },
      { "name": "_name", "type": "string", "internalType": "string" }
    ],
    "stateMutability": "nonpayable",
  },
  {
    "type": "fallback",
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "AUCTION",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IAuction" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "AUCTION_FACTORY",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IAuctionFactory" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "COLL",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract ERC20" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "COLL_PRICE_ORACLE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IPriceFeed" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_BUFFER_PERCENTAGE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_DUST_THRESHOLD",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "ORACLE_DOWN_BUFFER_PCT_MULTIPLIER",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "SP",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IStabilityPool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "allowDeposits",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "allowed",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "availableDepositLimit",
    "inputs": [{ "name": "_owner", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "availableWithdrawLimit",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "bufferPercentage",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "deployFunds",
    "inputs": [{ "name": "_amount", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "doHealthCheck",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "dustThreshold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "estimatedTotalAssets",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "freeFunds",
    "inputs": [{ "name": "_amount", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "harvestAndReport",
    "inputs": [],
    "outputs": [{ "name": "_totalAssets", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "isCollateralGainToClaim",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "lossLimitRatio",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "maxGasPriceToTend",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "openDeposits",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "profitLimitRatio",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "setAllowed",
    "inputs": [{ "name": "_address", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "setBufferPercentage",
    "inputs": [{ "name": "_bufferPercentage", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "setDoHealthCheck",
    "inputs": [{ "name": "_doHealthCheck", "type": "bool", "internalType": "bool" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "setDustThreshold",
    "inputs": [{ "name": "_dustThreshold", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "setLossLimitRatio",
    "inputs": [{ "name": "_newLossLimitRatio", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "setMaxGasPriceToTend",
    "inputs": [{ "name": "_maxGasPriceToTend", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "setProfitLimitRatio",
    "inputs": [{ "name": "_newProfitLimitRatio", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "shutdownWithdraw",
    "inputs": [{ "name": "_amount", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "sweep",
    "inputs": [{ "name": "_token", "type": "address", "internalType": "contract ERC20" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "tendThis",
    "inputs": [{ "name": "_totalIdle", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "tendTrigger",
    "inputs": [],
    "outputs": [
      { "name": "", "type": "bool", "internalType": "bool" },
      { "name": "", "type": "bytes", "internalType": "bytes" }
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "tokenizedStrategyAddress",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
]